version: '3.1'

services:
  mysql:
    image: mysql:5.7
    container_name: django-db
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: p@ssw0rd
      MYSQL_DATABASE: django-db
      MYSQL_USER: django
      MYSQL_PASSWORD: dJ@ng0-DB
